sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
before_script:
  - git config --global user.email "bot@turbot.com"
  - git config --global user.name "Turbot Bot (Travis CI)"
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    urls:
      - http://dx-helper.turbotapp.com/travis
