# @see https://mattbrictson.com/how-to-test-ruby-windows
# @see https://github.com/apiaryio/apiary-client/blob/master/appveyor.yml
version: '{build}'
skip_tags: true
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc
  - bundler --version
build_script:
  - bundle install
test_script:
  - bundle exec rake
artifacts:
  - path: pkg\*.gem
environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
